#pragma once

#define POSITION_SIZE  100.0f

#define GROUND_TYPE_COUNT	4
#define GROUND_SAND			0
#define GROUND_WATER		1
#define GROUND_GRASS		2
#define GROUND_GRASS2		3

#define OBJECT_TYPE_COUNT		5
#define OBJECT_TYPE_BUILDING	0
#define OBJECT_TYPE_SIMPLE		1
#define OBJECT_TYPE_UNIT		2
#define OBJECT_TYPE_PROJECTILE	3
#define OBJECT_TYPE_RESOURCE	4

#define DIRECTION_COUNT  8
#define DIRECTION_UP  0
#define DIRECTION_UP_RIGHT  1
#define DIRECTION_RIGHT  2
#define DIRECTION_DOWN_RIGHT  3
#define DIRECTION_DOWN  4
#define DIRECTION_DOWN_LEFT  5
#define DIRECTION_LEFT  6
#define DIRECTION_UP_LEFT  7


#define OBJECT_RESOURCE_TYPE_COUNT 3
#define OBJECT_RESOURCE_TYPE_FOOD 0
#define OBJECT_RESOURCE_TYPE_IRON 1
#define OBJECT_RESOURCE_TYPE_WOOD 2

#define OBJECT_RESOURCE_TYPE_WOOD_COUNT 3
#define OBJECT_RESOURCE_TYPE_WOOD_TREE1 0
#define OBJECT_RESOURCE_TYPE_WOOD_TREE2 1
#define OBJECT_RESOURCE_TYPE_WOOD_TREE3 2

#define OBJECT_RESOURCE_TYPE_FOOD_COUNT 3
#define OBJECT_RESOURCE_TYPE_FOOD_BUSH1 0
#define OBJECT_RESOURCE_TYPE_FOOD_BUSH2 1
#define OBJECT_RESOURCE_TYPE_FOOD_BUSH3 2

#define OBJECT_RESOURCE_TYPE_IRON_COUNT 3
#define OBJECT_RESOURCE_TYPE_IRON_STONE1 0
#define OBJECT_RESOURCE_TYPE_IRON_STONE2 1
#define OBJECT_RESOURCE_TYPE_IRON_STONE3 2


#define OBJECT_RESOURCE_STATE_HARVEST 1
#define OBJECT_RESOURCE_STATE_EMPTY 2


#define UNIT_TYPE_COUNT		3
#define UNIT_PEASANT		0
#define UNIT_SWORDSMAN		1
#define UNIT_ARCHER			2

#define SIMPLE_OBJECTS_COUNT 3
#define TREE1 0
#define GRASS01 1
#define GRASS02 2

#define TASK_TYPE_COUNT				6
#define TASK_TYPE_STAY				0
#define TASK_TYPE_MOVE				1
#define TASK_TYPE_ATTACK			2
#define TASK_TYPE_MOVE_TO_UNIT      3
#define TASK_TYPE_HARVEST			4
#define TASK_TYPE_BUILD				5

#define TASK_STATE_OK				1
#define TASK_STATE_CANCELLED		2
#define TASK_STATE_COMPLETED		3

#define ACTION_COUNT				11
#define ACTION_STAY					0
#define ACTION_MOVE					1
#define ACTION_HIT					2
#define ACTION_SHOOT				3
#define ACTION_DIE					4
#define ACTION_ATTACK				5
#define ACTION_HARVEST_WOOD			6
#define ACTION_HARVEST_IRON			7
#define ACTION_HARVEST_FOOD			8
#define ACTION_HARVEST_BUILD		9
#define ACTION_BUILD				10




#define BUILDING_TYPES_COUNT		8
#define BUILDING_POD				0
#define BUILDING_HOME				1
#define BUILDING_BARRACKS			2
#define BUILDING_STORE			    3
#define BUILDING_TOWER1			    4
#define BUILDING_CENTER				5
#define BUILDING_FENCE				6
#define BUILDING_FARM				7

#define FENCE_APPEARENCE_H			0
#define FENCE_APPEARENCE_V			1
#define FENCE_APPEARENCE_X			2
#define FENCE_APPEARENCE_T_UP		3
#define FENCE_APPEARENCE_T_RIGHT	4
#define FENCE_APPEARENCE_T_DOWN		5
#define FENCE_APPEARENCE_T_LEFT		6



#define PLAYER_COUNT 2

#define RELATION_NEUTRAL 0
#define RELATION_HOSTILE 1
#define RELATION_FRIENDLY 2


#define TOWN_TEMPLATE1   1


#define MAX_POPULATION 200