#pragma once


#define RESOURCE_CATEGORY_COUNT 4
#define RESOURCE_CATEGORY_TERRAIN 0
#define RESOURCE_CATEGORY_OBJECTS 1
#define RESOURCE_CATEGORY_GUI 2
#define RESOURCE_CATEGORY_TEMPLATES 3

#define RESOURCE_TYPE_COUNT 9 
#define RESOURCE_TYPE_TERRAIN 0 
#define RESOURCE_TYPE_SPRITE 1
#define RESOURCE_TYPE_ANIMATION 2 
#define RESOURCE_TYPE_DIRECT_ANIMATION 3 
#define RESOURCE_TYPE_IMAGE 4 
#define RESOURCE_TYPE_GUI 5
#define RESOURCE_TYPE_STATE_SPRITE 6
#define RESOURCE_TYPE_STATE_SPRITE_ARRAY 7
#define RESOURCE_TYPE_TOWN_TEMPLATE 8
